Tests removed from the release configuration build. This fixes errors Error CS0122:...is inaccessible due to its protection level. (Tests are not run in this build anyway.)